services:
  - type: web
    name: mi-proyecto-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DEBUG
        value: False